//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DalEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int IdCustomer { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public bool Enable { get; set; }
        public int Num1 { get; set; }
        public int Num2 { get; set; }
        public int Sum { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
    }
}
