//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DalEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int IdCustomer { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public bool Enable { get; set; }
        public int Num1 { get; set; }
        public int Num2 { get; set; }
        public int Sum { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
    }
}
